/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module cpu(i_clk, i_rst_n, i_i_valid_inst, i_i_inst, i_d_valid_data, i_d_data, o_i_valid_addr, o_i_addr, o_d_w_data, o_d_w_addr, o_d_r_addr, o_d_MemRead, o_d_MemWrite, o_finish);
  wire EXE_Finish;
  input i_clk;
  input [63:0] i_d_data;
  input i_d_valid_data;
  input [31:0] i_i_inst;
  input i_i_valid_inst;
  input i_rst_n;
  output o_d_MemRead;
  output o_d_MemWrite;
  output [63:0] o_d_r_addr;
  output [63:0] o_d_w_addr;
  output [63:0] o_d_w_data;
  output o_finish;
  output [63:0] o_i_addr;
  output o_i_valid_addr;
  assign EXE_Finish = 1'hx;
  assign o_d_MemRead = 1'hx;
  assign o_d_MemWrite = 1'hx;
  assign o_d_r_addr = 64'hxxxxxxxxxxxxxxxx;
  assign o_d_w_addr = 64'hxxxxxxxxxxxxxxxx;
  assign o_d_w_data = 64'hxxxxxxxxxxxxxxxx;
  assign o_finish = 1'hx;
  assign o_i_addr = 64'hxxxxxxxxxxxxxxxx;
  assign o_i_valid_addr = 1'hx;
endmodule
